### ISSUE TITLE
Method not found checkLocationSettingStatus

### ISSUE THREAD

**Issue by ghost** [Pulimet/GpsDetector-Library#2]
Hi.. As per your readme file, there is a method about checkLocationSettingStatus which is missing when i used the version net.alexandroid.utils:gps:1.6. Does this library open settings dialog or it enables the GPS silently ?

**Comment by Pulimet** [comment]
Hi, 
I am sorry but I forgot to update the name of the method in readme file, you should use checkGpsStatus().

If GPS enabled, library would invoke onGpsSettingStatus(boolean enabled) with true.
In case when GPS disabled it would show a dialog like this:
![3](https://user-images.githubusercontent.com/6112126/33162562-cefe95b0-d032-11e7-9ee0-b834c1b40bb5.jpg)
And if user accepted, the GPS is enabled.

Thank you

**Comment by ghost** [comment]
What is the minimum android version required for this ?

**Comment by Pulimet** [comment]
API 16+
